# Sun Choi: Py Schools Homework

#### Student and School Data Import and Cleanup

In [1]:
# import dependency
import pandas as pd

In [6]:
# import school and student files
school_data = pd.read_csv("Resources/schools_complete.csv")
student_data = pd.read_csv("Resources/students_complete.csv")

# create data frames for school and students
school_df = pd.DataFrame(school_data)
student_df = pd.DataFrame(student_data)

#for fun: clean up the suffixes and prefixes since these are kids
titles = [' MD', ' DDS', ' PhD', ' DVM', 'Dr. ', 'Mr. ', 'Ms. ', 'Mrs. ', 'Miss ']
#for fun: iterate through student column and replace the suffix and prefix errors 
for x in titles:
    student_df['student_name'] = student_df['student_name'].str.replace(x,"")
# check to see if for fun worked
print(student_df)

       Student ID     student_name gender grade         school_name  \
0               0     Paul Bradley      M   9th   Huang High School
1               1     Victor Smith      M  12th   Huang High School
2               2  Kevin Rodriguez      M  12th   Huang High School
3               3    Richard Scott      M  12th   Huang High School
4               4       Bonnie Ray      F   9th   Huang High School
...           ...              ...    ...   ...                 ...
39165       39165     Donna Howard      F  12th  Thomas High School
39166       39166        Dawn Bell      F  10th  Thomas High School
39167       39167   Rebecca Tanner      F   9th  Thomas High School
39168       39168     Desiree Kidd      F  10th  Thomas High School
39169       39169  Carolyn Jackson      F  11th  Thomas High School

       reading_score  math_score
0                 66          79
1                 94          61
2                 90          60
3                 67          58
4                 97          84
...              ...         ...
39165             99          90
39166             95          70
39167             73          84
39168             99          90
39169             95          75

[39170 rows x 7 columns]

In [7]:
# inner join data on school_name
merge_df = pd.merge(school_df, student_df, how='inner', on=["school_name"])
# merge_df.head()

### District Summary Asks
1. Total number of unique schools
2. Total students
3. Total budget
4. Average math score
5. Average reading score
6. % passing math (the percentage of students who passed math)
7. % passing reading (the percentage of students who passed reading)
8. % overall passing (the percentage of students who passed math AND reading)

#### Calculations for District Summary

In [8]:
# 1.Unique Schools from merged dataset and count of unique schools
unique_schools = merge_df["school_name"].unique()
count_unique_schools = merge_df["school_name"].nunique()
# print(unique_schools)
# print(count_unique_schools)

# 2.Total Students
student_count = merge_df['student_name'].count()
# print(f'Total Students: {student_count:,d}')

# 3.Total Budget
total_budget = school_df['budget'].sum()
# print(f'Total Budget: ${total_budget:,d}')

# 4.Average Math Score
avg_math_score = round(merge_df['math_score'].mean(),3)
# print(avg_math_score)

# 5.Average Reading Score
avg_read_score = round(merge_df['reading_score'].mean(),3)
# print(avg_read_score)

# 6. % passing math (the percentage of students who passed math)
pass_math_score_df = merge_df.loc[merge_df['math_score'] >= 70].count()['math_score']
percent_passed_math = (pass_math_score_df/student_count)*100
# print(f'Number of students who passed math: {pass_math_score_df}')
# print(f'Percent Passed Math: {percent_passed_math}%')

# 7. % passing reading (the percentage of students who passed reading)
pass_read_score_df = merge_df.loc[merge_df['reading_score']>= 70].count()['reading_score']
percent_passed_reading = (pass_read_score_df/student_count)*100
# print(f'Number of total students who passed reading: {pass_read_score_df}')
# print(f'Percent Passed Reading: {percent_passed_reading}')

# 8. % overall passing (the percentage of students who passed math AND reading)
pass_both_score_df = merge_df.loc[(merge_df['reading_score']>= 70) & (merge_df['math_score'] >= 70)].count()['student_name']
percent_passed_both = (pass_both_score_df/student_count)*100
# print(f'number of students passed both math and reading: {pass_both_score_df}')
# print(f'Percent of students who passed both: {percent_passed_both}%')

# District Summary

#### Step 3: Summarize District Asks

In [9]:
# create table
district_summary = pd.DataFrame([{'Total Schools': count_unique_schools, 'Total Students': student_count, 
                                  'Total Budget': total_budget, 'Average Math Score':avg_math_score,
                                  'Average Reading Score': avg_read_score, 'Percent of Students Passed Math':percent_passed_math,
                                  'Percent of Students Passed Reading': percent_passed_reading, 
                                  'Percent of Students Passed Both':percent_passed_both
                                 }])

# Format DataFrame
district_summary['Total Students'] = district_summary['Total Students'].map('{:,}'.format)
district_summary['Total Budget'] = district_summary['Total Budget'].map('${:,.2f}'.format)
district_summary['Average Math Score'] = district_summary['Average Math Score'].map('{:,.2f}%'.format)
district_summary['Average Reading Score'] = district_summary['Average Reading Score'].map('{:,.2f}%'.format)
district_summary['Percent of Students Passed Math'] = district_summary['Percent of Students Passed Math'].map('{:,.2f}%'.format)
district_summary['Percent of Students Passed Reading'] = district_summary['Percent of Students Passed Reading'].map('{:,.2f}%'.format)
district_summary['Percent of Students Passed Both'] = district_summary['Percent of Students Passed Both'].map('{:,.2f}%'.format)

#Print DataFrame
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,Percent of Students Passed Math,Percent of Students Passed Reading,Percent of Students Passed Both
0,15,"39,170","$24,649,428.00",78.98%,81.88%,74.98%,85.81%,65.17%

### School Summary Asks
1. Use the code provided to select the school type (2 points)
2. Calculate the total student count (2 points)
3. Use the code provided to calculate the per capita spending (2 points)
4. Calculate the average test scores (2 points)
5. Calculate the number of schools with math scores of 70 or higher (2 points)
6. Calculate the number of schools with reading scores of 70 or higher (2 points)
7. Use the provided code to calculate the schools that passed both math and reading with scores of 70 or higher (2 points)
8. Use the provided code to calculate the passing rates (2 points)
9. Create a new DataFrame for the above calculations called per_school_summary (4 points)

#### Calculations

In [6]:
# 1. Use code provided to select the school type
school_types = school_df.set_index(['school_name'])['type']
#print(school_types)

# 2. Calculate the total student count
per_school_count = merge_df['school_name'].value_counts()
# print(per_school_count)

# 3. Use code to calculate per capita spending
per_school_budget = merge_df.groupby(['school_name']).mean()['budget']
per_school_capita = per_school_budget / per_school_count
#print(per_school_budget)
#print(per_school_capita)

# 4. Average Test Scores by School
school_avg_read_score = merge_df.groupby(['school_name']).mean()['reading_score']
school_avg_math_score = merge_df.groupby(['school_name']).mean()['math_score']
# print(school_avg_read_score)
# print(school_avg_math_score)

#5. Calculate the number of schools with math scores of 70 or higher
schools_passing_math = merge_df[(merge_df['math_score']>=70)].sort_values(by=['math_score'])
# print(schools_passing_math)

#6. Calculate the number of schools with read scores of 70 or higher
schools_passing_reading = merge_df[(merge_df['reading_score']>=70)].sort_values(by=['reading_score'])
# print(schools_passing_reading)

# 7.Use the provided code to calculate the schools that passed both math and reading with scores of 70 or higher
schools_pass_both = merge_df[(merge_df['math_score']>=70) & (merge_df['reading_score']>=70)].sort_values(by=['reading_score', 'math_score'])
# print(schools_pass_both)

# 8.calculate passing rates of math, reading and both by schools
per_school_passing_math = (schools_passing_math.groupby(['school_name']).count()['student_name']/per_school_count)*100
per_school_passing_reading = (schools_passing_reading.groupby(['school_name']).count()['student_name']/per_school_count)*100
per_school_passing_both = (schools_pass_both.groupby(['school_name']).count()['student_name']/per_school_count)*100
# print(per_school_passing_math)

# Per School Summary

In [20]:
# 9. Create Per School Summary
# create table to hold data to be used in other summary data
per_school_summary_df = pd.DataFrame({'School Type':school_types,'Total Student Count': per_school_count,
                                   'Per Capita Spending': per_school_capita, 
                                   'Average Math Test Scores':school_avg_math_score,
                                   'Average Reading Test Scores': school_avg_read_score,
                                   'Math Test Passing Rate': per_school_passing_math,
                                   'Reading Test Passing Rate':per_school_passing_reading, 
                                   'Reading and Math Test Passing Rate': per_school_passing_both
    
})

# store data to be used in per school summary
per_school_summary = per_school_summary_df.copy()

# format the numbers
per_school_summary['Total Student Count'] = per_school_summary['Total Student Count'].map('{:,}'.format)
per_school_summary['Per Capita Spending'] = per_school_summary['Per Capita Spending'].map('${:,}'.format)
per_school_summary['Average Reading Test Scores'] = per_school_summary['Average Reading Test Scores'].map('{:,.2f}%'.format)
per_school_summary['Average Math Test Scores'] = per_school_summary['Average Math Test Scores'].map('{:,.2f}%'.format)
per_school_summary['Math Test Passing Rate'] = per_school_summary['Math Test Passing Rate'].map('{:,.2f}%'.format)
per_school_summary['Reading Test Passing Rate'] = per_school_summary['Reading Test Passing Rate'].map('{:,.2f}%'.format)
per_school_summary['Reading and Math Test Passing Rate'] = per_school_summary['Reading and Math Test Passing Rate'].map('{:,.2f}%'.format)
  
# display results
per_school_summary

,School Type,Total Student Count,Per Capita Spending,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
Bailey High School,District,"4,976",$628.0,77.05%,81.03%,66.68%,81.93%,54.64%
Cabrera High School,Charter,"1,858",$582.0,83.06%,83.98%,94.13%,97.04%,91.33%
Figueroa High School,District,"2,949",$639.0,76.71%,81.16%,65.99%,80.74%,53.20%
Ford High School,District,"2,739",$644.0,77.10%,80.75%,68.31%,79.30%,54.29%
Griffin High School,Charter,"1,468",$625.0,83.35%,83.82%,93.39%,97.14%,90.60%
Hernandez High School,District,"4,635",$652.0,77.29%,80.93%,66.75%,80.86%,53.53%
Holden High School,Charter,427,$581.0,83.80%,83.81%,92.51%,96.25%,89.23%
Huang High School,District,"2,917",$655.0,76.63%,81.18%,65.68%,81.32%,53.51%
Johnson High School,District,"4,761",$650.0,77.07%,80.97%,66.06%,81.22%,53.54%
Pena High School,Charter,962,$609.0,83.84%,84.04%,94.59%,95.95%,90.54%
Rodriguez High School,District,"3,999",$637.0,76.84%,80.74%,66.37%,80.22%,52.99%
Shelton High School,Charter,"1,761",$600.0,83.36%,83.73%,93.87%,95.85%,89.89%
Thomas High School,Charter,"1,635",$638.0,83.42%,83.85%,93.27%,97.31%,90.95%
Wilson High School,Charter,"2,283",$578.0,83.27%,83.99%,93.87%,96.54%,90.58%
Wright High School,Charter,"1,800",$583.0,83.68%,83.95%,93.33%,96.61%,90.33%

# Highest-Performing Schools by Percentage of Overall Passing

In [25]:
# sort schools by top 5 performing in both math and reading in descending
top_5_schools_df = pd.DataFrame(per_school_summary.sort_values(
    by=['Reading and Math Test Passing Rate'],ascending=False).head()
                               )
top_5_schools_df

,School Type,Total Student Count,Per Capita Spending,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
Cabrera High School,Charter,"1,858",$582.0,83.06%,83.98%,94.13%,97.04%,91.33%
Thomas High School,Charter,"1,635",$638.0,83.42%,83.85%,93.27%,97.31%,90.95%
Griffin High School,Charter,"1,468",$625.0,83.35%,83.82%,93.39%,97.14%,90.60%
Wilson High School,Charter,"2,283",$578.0,83.27%,83.99%,93.87%,96.54%,90.58%
Pena High School,Charter,962,$609.0,83.84%,84.04%,94.59%,95.95%,90.54%

# Lowest-Performing Schools by Percentage of Overall Passing

In [22]:
# sort schools by bottom 5 performing in both math and reading in ascending
bottom_5_schools_df = pd.DataFrame(per_school_summary.sort_values(by=['Reading and Math Test Passing Rate']).head())
bottom_5_schools_df

,School Type,Total Student Count,Per Capita Spending,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
Rodriguez High School,District,"3,999",$637.0,76.84%,80.74%,66.37%,80.22%,52.99%
Figueroa High School,District,"2,949",$639.0,76.71%,81.16%,65.99%,80.74%,53.20%
Huang High School,District,"2,917",$655.0,76.63%,81.18%,65.68%,81.32%,53.51%
Hernandez High School,District,"4,635",$652.0,77.29%,80.93%,66.75%,80.86%,53.53%
Johnson High School,District,"4,761",$650.0,77.07%,80.97%,66.06%,81.22%,53.54%

# Math Scores by Grade

In [10]:
#seperate data by grades
ninth_graders = merge_df[(merge_df['grade']=='9th')]
tenth_graders = merge_df[(merge_df['grade']=='10th')]
eleventh_graders = merge_df[(merge_df['grade']=='11th')]
twelveth_graders = merge_df[(merge_df['grade']=='12th')]

# group grades and scores by school
ninth_grade_math_scores = ninth_graders.groupby(['school_name']).mean()['math_score']
tenth_grade_math_scores = tenth_graders.groupby(['school_name']).mean()['math_score']
eleventh_grade_math_scores = eleventh_graders.groupby(['school_name']).mean()['math_score']
twelveth_grade_math_scores = twelveth_graders.groupby(['school_name']).mean()['math_score']

# assign math scores as dataframe
math_scores_by_grade = pd.DataFrame({'9th':ninth_grade_math_scores.map('{:,.2f}%'.format),
                                     '10th':tenth_grade_math_scores.map('{:,.2f}%'.format),
                                     '11th':eleventh_grade_math_scores.map('{:,.2f}%'.format),
                                     '12th':twelveth_grade_math_scores.map('{:,.2f}%'.format)
                                    })

# reset index to none
math_scores_by_grade.index.name = None

#print results
math_scores_by_grade

                          9th    10th    11th    12th
Bailey High School     77.08%  77.00%  77.52%  76.49%
Cabrera High School    83.09%  83.15%  82.77%  83.28%
Figueroa High School   76.40%  76.54%  76.88%  77.15%
Ford High School       77.36%  77.67%  76.92%  76.18%
Griffin High School    82.04%  84.23%  83.84%  83.36%
Hernandez High School  77.44%  77.34%  77.14%  77.19%
Holden High School     83.79%  83.43%  85.00%  82.86%
Huang High School      77.03%  75.91%  76.45%  77.23%
Johnson High School    77.19%  76.69%  77.49%  76.86%
Pena High School       83.63%  83.37%  84.33%  84.12%
Rodriguez High School  76.86%  76.61%  76.40%  77.69%
Shelton High School    83.42%  82.92%  83.38%  83.78%
Thomas High School     83.59%  83.09%  83.50%  83.50%
Wilson High School     83.09%  83.72%  83.20%  83.04%
Wright High School     83.26%  84.01%  83.84%  83.64%

# Reading Scores by Grade

In [11]:
#seperate data by grades
ninth_graders = merge_df[(merge_df['grade']=='9th')]
tenth_graders = merge_df[(merge_df['grade']=='10th')]
eleventh_graders = merge_df[(merge_df['grade']=='11th')]
twelveth_graders = merge_df[(merge_df['grade']=='12th')]

#group grades and scores by school
ninth_grade_reading_scores = ninth_graders.groupby(['school_name']).mean()['reading_score']
tenth_grade_reading_scores = tenth_graders.groupby(['school_name']).mean()['reading_score']
eleventh_grade_reading_scores = eleventh_graders.groupby(['school_name']).mean()['reading_score']
twelveth_grade_reading_scores = twelveth_graders.groupby(['school_name']).mean()['reading_score']

# assign reading scores as dataframe
reading_scores_by_grade = pd.DataFrame({'9th':ninth_grade_reading_scores.map('{:,.2f}%'.format),
                                     '10th':tenth_grade_reading_scores.map('{:,.2f}%'.format),
                                     '11th':eleventh_grade_reading_scores.map('{:,.2f}%'.format),
                                     '12th':twelveth_grade_reading_scores.map('{:,.2f}%'.format)
                                    })

# reset index to none
reading_scores_by_grade.index.name = None

#print results
reading_scores_by_grade

                          9th    10th    11th    12th
Bailey High School     81.30%  80.91%  80.95%  80.91%
Cabrera High School    83.68%  84.25%  83.79%  84.29%
Figueroa High School   81.20%  81.41%  80.64%  81.38%
Ford High School       80.63%  81.26%  80.40%  80.66%
Griffin High School    83.37%  83.71%  84.29%  84.01%
Hernandez High School  80.87%  80.66%  81.40%  80.86%
Holden High School     83.68%  83.32%  83.82%  84.70%
Huang High School      81.29%  81.51%  81.42%  80.31%
Johnson High School    81.26%  80.77%  80.62%  81.23%
Pena High School       83.81%  83.61%  84.34%  84.59%
Rodriguez High School  80.99%  80.63%  80.86%  80.38%
Shelton High School    84.12%  83.44%  84.37%  82.78%
Thomas High School     83.73%  84.25%  83.59%  83.83%
Wilson High School     83.94%  84.02%  83.76%  84.32%
Wright High School     83.83%  83.81%  84.16%  84.07%

# Scores by School Spending

In [17]:
# Establish the bins 
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

# Create a copy of the school summary since it has the "Per Student Budget" 
school_spending_df = per_school_summary_df.copy()

# Use `pd.cut` to categorize spending based on the bins.
school_spending_df["Spending Ranges (Per Student)"] = pd.cut(per_school_capita,spending_bins,labels=labels)

#  Calculate averages for the desired columns. 
spending_math_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Math Test Scores"]
spending_reading_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Average Reading Test Scores"]
spending_passing_math = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Math Test Passing Rate"]
spending_passing_reading = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()["Reading Test Passing Rate"]
overall_passing_spending = school_spending_df.groupby(["Spending Ranges (Per Student)"]).mean()['Reading and Math Test Passing Rate']

# assign school spending as dataframe
spending_summary = pd.DataFrame({ "Average Math Test Scores":spending_math_scores.map('{:,.2f}%'.format),
                                'Average Reading Test Scores':spending_reading_scores.map('{:,.2f}%'.format),
                                'Math Test Passing Rate':spending_passing_math.map('{:,.2f}%'.format),
                                'Reading Test Passing Rate':spending_passing_reading.map('{:,.2f}%'.format),
                                'Reading and Math Test Passing Rate':overall_passing_spending.map('{:,.2f}%'.format)
                                })
#print results
spending_summary

,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
Spending Ranges (Per Student),,,,,
<$585,83.46%,83.93%,93.46%,96.61%,90.37%
$585-630,81.90%,83.16%,87.13%,92.72%,81.42%
$630-645,78.52%,81.62%,73.48%,84.39%,62.86%
$645-680,77.00%,81.03%,66.16%,81.13%,53.53%

# Scores by School Size

In [18]:
# Establish the bins.
size_bins = [0, 1000, 2000, 5000]
labels = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

# Categorize the spending based on the bins
# Use `pd.cut` on the "Total Students" column of the `per_school_summary` DataFrame.
per_school_summary_df["Total Student Count"] = pd.cut(per_school_count,size_bins, labels=labels)

# Calculate averages for the desired columns. 
size_math_scores = per_school_summary_df.groupby(["Total Student Count"]).mean()["Average Math Test Scores"]
size_reading_scores = per_school_summary_df.groupby(["Total Student Count"]).mean()["Average Reading Test Scores"]
size_passing_math = per_school_summary_df.groupby(["Total Student Count"]).mean()["Math Test Passing Rate"]
size_passing_reading = per_school_summary_df.groupby(["Total Student Count"]).mean()["Reading Test Passing Rate"]
size_overall_passing = per_school_summary_df.groupby(["Total Student Count"]).mean()["Reading and Math Test Passing Rate"]


# assign school size as dataframe
size_summary = pd.DataFrame({ "Average Math Test Scores":size_math_scores.map('{:,.2f}%'.format),
                                'Average Reading Test Scores':size_reading_scores.map('{:,.2f}%'.format),
                                'Math Test Passing Rate':size_passing_math.map('{:,.2f}%'.format),
                                'Reading Test Passing Rate':size_passing_reading.map('{:,.2f}%'.format),
                                'Reading and Math Test Passing Rate':size_overall_passing.map('{:,.2f}%'.format)
                                })
size_summary

,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
Total Student Count,,,,,
Small (<1000),83.82%,83.93%,93.55%,96.10%,89.88%
Medium (1000-2000),83.37%,83.86%,93.60%,96.79%,90.62%
Large (2000-5000),77.75%,81.34%,69.96%,82.77%,58.29%

# Scores by School Type

In [19]:
# Calculate averages for the desired columns. 
type_math_scores = per_school_summary_df.groupby(["School Type"]).mean()["Average Math Test Scores"]
type_reading_scores = per_school_summary_df.groupby(["School Type"]).mean()["Average Reading Test Scores"]
type_passing_math = per_school_summary_df.groupby(["School Type"]).mean()["Math Test Passing Rate"]
type_passing_reading = per_school_summary_df.groupby(["School Type"]).mean()["Reading Test Passing Rate"]
type_overall_passing = per_school_summary_df.groupby(["School Type"]).mean()["Reading and Math Test Passing Rate"]

# assign school size as dataframe
type_summary = pd.DataFrame({ "Average Math Test Scores":type_math_scores.map('{:,.2f}%'.format),
                                'Average Reading Test Scores':type_reading_scores.map('{:,.2f}%'.format),
                                'Math Test Passing Rate':type_passing_math.map('{:,.2f}%'.format),
                                'Reading Test Passing Rate':type_passing_reading.map('{:,.2f}%'.format),
                                'Reading and Math Test Passing Rate':type_overall_passing.map('{:,.2f}%'.format)
                                })
type_summary

,Average Math Test Scores,Average Reading Test Scores,Math Test Passing Rate,Reading Test Passing Rate,Reading and Math Test Passing Rate
School Type,,,,,
Charter,83.47%,83.90%,93.62%,96.59%,90.43%
District,76.96%,80.97%,66.55%,80.80%,53.67%

# Written Report

In [16]:
district_summary
district_summary_analysis = 'The District Summary output gives us a high-level view of how many schools, the combined budget, average test scores, and percent of students who passed in the test categories within the district'
spending_summary
spending_summary_analysis = 'the School Summary output shows the reader how much money schools can spend per student, what the average test scores and passing rates are based on each school'
top_5_schools_df
top_5_analysis = 'The Top 5 view shows us the 5 highest performing schools by overall passing rate performance'
bottom_5_schools_df
bot_5_analysis = 'The Bottom 5 view shows us the 5 lowest performing schools by overall passing rate performance'
math_scores_by_grade
math_scores_grade_analysis = 'Math Scores by Grade is a breakdown of average math test scores by grade for each school'
reading_scores_by_grade
reading_score_analysis = 'Reading Scores by Grade is a breakdown of average reading test scores by grade for each school'
size_summary
size_summary_analysis = 'The Size Summary table shows the average test scores and passing rates of students based on their school size grouping'
type_summary
type_summary_analysis = 'The Type Summary table shows the average test scores and passing rates of students based on their school type'
conclusions = 'The conclusions we can draw from the multiple analyses are as follows: overall, charter schools outperform district schools in all categories, specifically passing rates. Large Schools have the lowest passing rates possibly due to larger classrooms per teacher, but that is an assumption. Medium sized charter schools are the 3 top performing schools in this district. More spending doesnt mean better test results, what is more important is the type and size of the school for outcomes.'